CREATE DATABASE QuanLyBanVeMayBay
USE QuanLyBanVeMayBay

-- Tạo bảng MAYBAY
CREATE TABLE MAYBAY (
	MAMB CHAR(8) PRIMARY KEY,
	TENMAYBAY VARCHAR(40) NOT NULL,
	HANGSANXUAT VARCHAR(50) NOT NULL,
	SOGHETHUONG INT,
	SOGHEVIP INT
);

-- Tạo bảng SANBAY
CREATE TABLE SANBAY (
	MASB CHAR(8) PRIMARY KEY,
	TENSB NVARCHAR(40) NOT NULL
);

-- Tạo bảng TUYENBAY
CREATE TABLE TUYENBAY (
	MATB CHAR(8) PRIMARY KEY,
	MASBDI CHAR(8) FOREIGN KEY REFERENCES SANBAY(MASB),
	MASBDEN CHAR(8) FOREIGN KEY REFERENCES SANBAY(MASB)
);

-- Tạo bảng CHUYENBAY
CREATE TABLE CHUYENBAY (
	MACB CHAR(8) PRIMARY KEY,
	MATB CHAR(8) FOREIGN KEY REFERENCES TUYENBAY(MATB),
	MAMB CHAR(8) FOREIGN KEY REFERENCES MAYBAY(MAMB),
	NGAYKHOIHANH SMALLDATETIME NOT NULL,
	GIOKHOIHANH SMALLDATETIME NOT NULL,
	THOIGIANDUKIEN TIME NOT NULL,
	DIEMDI NVARCHAR(40) NOT NULL,
	DIEMDEN NVARCHAR(40) NOT NULL,
	SOGHEHANGTHUONGCONLAI INT,
	SOGHEHANGVIPCONLAI INT
);

-- Tạo bảng VAITRO
CREATE TABLE VAITRO (
	MAVT CHAR(8) PRIMARY KEY,
	TENVAITRO VARCHAR(50) NOT NULL
);

-- Tạo bảng NHANVIEN
CREATE TABLE NHANVIEN (
	MANV CHAR(8) PRIMARY KEY,
	TENNV NVARCHAR(30) NOT NULL,
	DIACHI NCHAR(50),
	SODT VARCHAR(10) UNIQUE,
	NGAYSINH SMALLDATETIME NOT NULL,
	NGAYVAOLAM SMALLDATETIME NOT NULL,
	GIOITINH NCHAR(3) NOT NULL,
	EMAIL VARCHAR(50) UNIQUE,
	PASSWORD VARCHAR(25) NOT NULL,
	NGAYTAOTK DATETIME NOT NULL,
	MAVT CHAR(8) REFERENCES VAITRO(MAVT)
);

-- Tạo bảng KHACHHANG
CREATE TABLE KHACHHANG (
	MAKH CHAR(8) PRIMARY KEY,
	TENKH NVARCHAR(30) NOT NULL,
	GIOITINH NCHAR(3) NOT NULL,
	NGAYSINH SMALLDATETIME NOT NULL,
	CCCD NVARCHAR(12) UNIQUE,
	NGAYCAP SMALLDATETIME NOT NULL,
	QUOCTICH NVARCHAR(30) NOT NULL,
	SODT VARCHAR(10) UNIQUE,
	EMAIL VARCHAR(50) UNIQUE,
	DIACHI NCHAR(50) NOT NULL,
	PASSWORD VARCHAR(25) NOT NULL,
	NGAYTAOTK DATETIME NOT NULL,
	MAVT CHAR(8) REFERENCES VAITRO(MAVT)
);

-- Tạo bảng HANGVE
CREATE TABLE HANGVE (
	MAHV CHAR(8) PRIMARY KEY,
	TENHANGVE NVARCHAR(20) NOT NULL
);

-- Tạo bảng VE
CREATE TABLE VE (
	MAVE CHAR(8) PRIMARY KEY,
	MAHV CHAR(8) FOREIGN KEY REFERENCES HANGVE(MAHV),
	MACB CHAR(8) FOREIGN KEY REFERENCES CHUYENBAY(MACB),
	MAKH CHAR(8) FOREIGN KEY REFERENCES KHACHHANG(MAKH),
	MANV CHAR(8) FOREIGN KEY REFERENCES NHANVIEN(MANV),
	GHE INT UNIQUE,
	GIAVE MONEY NOT NULL
	TINHTRANGDATVE BOOLEAN
	NGAYLAPVE SMALLDATETIME
);

-- Tạo dữ liệu mẫu


DELIMITER //
CREATE FUNCTION SoLuong_KH_TrongThang (
	p_month INT;
	p_year INT
)
RETURNS INT
DETERMINISTIC
READS SQL DATA
BEGIN 
	DECLARE SLKH INT;
	SELECT COUNT(*) INTO SLKH
	FROM KHACHHANG
	WHERE MONTH(NGAYTAOTK) = p_month AND YEAR(NGAYTAOTK) = p_year;
	RETURN SLKH;
END //
DELIMITER;

