-- Tạo role
CREATE ROLE 'admin_role';
CREATE ROLE 'nhanvien_role';
CREATE ROLE 'khachhang_role';

-- Tạo user
CREATE USER 'admin_user'@'%' IDENTIFIED BY 'yourAdminPassword';
CREATE USER 'nhanvien_user'@'%' IDENTIFIED BY 'yourNhanVienPassword';
CREATE USER 'khachhang_user'@'%' IDENTIFIED BY 'yourKhachHangPassword';

-- Gán role cho user
GRANT 'admin_role' TO 'admin_user'@'%';
GRANT 'nhanvien_role' TO 'nhanvien_user'@'%';
GRANT 'khachhang_role' TO 'khachhang_user'@'%';

-- Cấp quyền quản lý toàn bộ database cho admin
GRANT ALL PRIVILEGES ON QUANLYCHUYENBAY.* TO 'admin_role';

-- Cấp quyền thao tác trên bảng cho nhân viên
GRANT SELECT, INSERT, UPDATE, DELETE ON QUANLYCHUYENBAY.CHUYENBAY TO 'nhanvien_role';
GRANT SELECT, INSERT, UPDATE, DELETE ON QUANLYCHUYENBAY.HOADON TO 'nhanvien_role';
GRANT SELECT, INSERT, UPDATE, DELETE ON QUANLYCHUYENBAY.VE TO 'nhanvien_role';
GRANT SELECT, INSERT, UPDATE, DELETE ON QUANLYCHUYENBAY.KHACHHANG TO 'nhanvien_role';
GRANT SELECT, INSERT, UPDATE, DELETE ON QUANLYCHUYENBAY.SANBAY TO 'nhanvien_role';
GRANT SELECT, INSERT, UPDATE, DELETE ON QUANLYCHUYENBAY.TUYENBAY TO 'nhanvien_role';
GRANT SELECT, INSERT, UPDATE, DELETE ON QUANLYCHUYENBAY.NHANVIEN TO 'nhanvien_role';
GRANT SELECT, INSERT, UPDATE, DELETE ON QUANLYCHUYENBAY.MAYBAY TO 'nhanvien_role';

-- Cấp quyền xem các bảng cho khách hàng
GRANT SELECT ON QUANLYCHUYENBAY.CHUYENBAY TO 'khachhang_role';
GRANT SELECT ON QUANLYCHUYENBAY.VE TO 'khachhang_role';
GRANT SELECT ON QUANLYCHUYENBAY.HOADON TO 'khachhang_role';
GRANT SELECT ON QUANLYCHUYENBAY.KHACHHANG TO 'khachhang_role';

-- Cấp quyền thực thi function cho nhân viên
GRANT EXECUTE ON FUNCTION QUANLYCHUYENBAY.DEM_SLKHDK_THEOTHANG TO 'nhanvien_role';
GRANT EXECUTE ON FUNCTION QUANLYCHUYENBAY.DEM_SLCB_THEOTHANG TO 'nhanvien_role';
GRANT EXECUTE ON FUNCTION QUANLYCHUYENBAY.DOANHTHU TO 'nhanvien_role';

-- Cấp quyền thực thi procedure cho nhân viên
GRANT EXECUTE ON PROCEDURE QUANLYCHUYENBAY.PRC_DanhSach_KhachHang TO 'nhanvien_role';
GRANT EXECUTE ON PROCEDURE QUANLYCHUYENBAY.PRC_DanhSach_NhanVien TO 'nhanvien_role';
GRANT EXECUTE ON PROCEDURE QUANLYCHUYENBAY.PRC_DanhSach_HoaDon_NhanVien_DaTao TO 'nhanvien_role';
GRANT EXECUTE ON PROCEDURE QUANLYCHUYENBAY.PRC_DanhSach_HoaDon_KhachHang_DaThanhToan TO 'nhanvien_role';
GRANT EXECUTE ON PROCEDURE QUANLYCHUYENBAY.PRC_DanhSach_ChuyenBay_TheoNgay TO 'nhanvien_role';
GRANT EXECUTE ON PROCEDURE QUANLYCHUYENBAY.PRC_DanhSach_ChuyenBay TO 'nhanvien_role';
GRANT EXECUTE ON PROCEDURE QUANLYCHUYENBAY.PRC_DanhSach_Ve_Theo_MACB TO 'nhanvien_role';
GRANT EXECUTE ON PROCEDURE QUANLYCHUYENBAY.PRC_ThemMoi_NhanVien TO 'nhanvien_role';
GRANT EXECUTE ON PROCEDURE QUANLYCHUYENBAY.PRC_ThemMoi_ChuyenBay TO 'nhanvien_role';
GRANT EXECUTE ON PROCEDURE QUANLYCHUYENBAY.PRC_ThemMoi_KhachHang TO 'nhanvien_role';
GRANT EXECUTE ON PROCEDURE QUANLYCHUYENBAY.PRC_ThemMoi_Ve TO 'nhanvien_role';
GRANT EXECUTE ON PROCEDURE QUANLYCHUYENBAY.PRC_ThemMoi_HoaDon TO 'nhanvien_role';
GRANT EXECUTE ON PROCEDURE QUANLYCHUYENBAY.PRC_TongTienDaMua TO 'nhanvien_role';
GRANT EXECUTE ON PROCEDURE QUANLYCHUYENBAY.PRC_CapNhat_GiaVe TO 'nhanvien_role';
GRANT EXECUTE ON PROCEDURE QUANLYCHUYENBAY.TIM_CHUYENBAY TO 'nhanvien_role';

-- Cấp quyền thực thi procedure cho khách hàng
GRANT EXECUTE ON PROCEDURE QUANLYCHUYENBAY.PRC_DanhSach_ChuyenBay TO 'khachhang_role';
GRANT EXECUTE ON PROCEDURE QUANLYCHUYENBAY.PRC_DanhSach_HoaDon_KhachHang_DaThanhToan TO 'khachhang_role';
GRANT EXECUTE ON PROCEDURE QUANLYCHUYENBAY.PRC_DanhSach_Ve_Theo_MACB TO 'khachhang_role';
GRANT EXECUTE ON PROCEDURE QUANLYCHUYENBAY.PRC_DanhSach_ChuyenBay_TheoNgay TO 'khachhang_role';
GRANT EXECUTE ON PROCEDURE QUANLYCHUYENBAY.PRC_TongTienDaMua TO 'khachhang_role';
GRANT EXECUTE ON PROCEDURE QUANLYCHUYENBAY.PRC_DanhSach_KhachHang TO 'khachhang_role';
GRANT EXECUTE ON PROCEDURE QUANLYCHUYENBAY.TIM_CHUYENBAY TO 'khachhang_role';

-- Apply changes
FLUSH PRIVILEGES;
