CREATE DATABASE QUANLYCHUYENBAY;
GO

USE QUANLYCHUYENBAY;
GO

CREATE TABLE MAYBAY (
    MAMB CHAR(8) PRIMARY KEY,
    TENMAYBAY NVARCHAR(40) NOT NULL,
    HANGSANXUAT NVARCHAR(50) NOT NULL,
    SOGHETHUONG INT NOT NULL,
    SOGHEVIP INT NOT NULL
);
GO

CREATE TABLE SANBAY (
    MASB CHAR(3) PRIMARY KEY,
    TENSB NVARCHAR(40) NOT NULL,
	DIADIEM NVARCHAR(40) NOT NULL
);
GO

CREATE TABLE TUYENBAY (
    MATB CHAR(8) PRIMARY KEY,
    MASBDI CHAR(3) FOREIGN KEY REFERENCES SANBAY(MASB),
    MASBDEN CHAR(3) FOREIGN KEY REFERENCES SANBAY(MASB)
);
GO

CREATE TABLE CHUYENBAY (
    MACB CHAR(8) PRIMARY KEY,
    MATB CHAR(8) FOREIGN KEY REFERENCES TUYENBAY(MATB),
    MAMB CHAR(8) FOREIGN KEY REFERENCES MAYBAY(MAMB),
    NGAYKHOIHANH DATE NOT NULL,
    GIOKHOIHANH TIME NOT NULL,
    THOIGIANDUKIEN TIME NOT NULL,
	GIOHACANH TIME,
    SOGHEHANGTHUONGCONLAI INT,
    SOGHEHANGVIPCONLAI INT
);
GO

CREATE TABLE VAITRO (
    MAVT CHAR(8) PRIMARY KEY,
    TENVAITRO VARCHAR(50) NOT NULL
);
GO

CREATE TABLE NHANVIEN (
    MANV CHAR(8) PRIMARY KEY,
    TENNV NVARCHAR(30) NOT NULL,
    DIACHI NCHAR(50) NOT NULL,
    SODT VARCHAR(10) UNIQUE,
    NGAYSINH SMALLDATETIME NOT NULL,
    NGAYVAOLAM SMALLDATETIME NOT NULL,
    GIOITINH NCHAR(3) NOT NULL,
    EMAIL VARCHAR(50) UNIQUE,
    PASSWORD VARCHAR(25) NOT NULL,
    NGAYTAOTK DATETIME NOT NULL,
    MAVT CHAR(8) FOREIGN KEY REFERENCES VAITRO(MAVT)
);
GO

CREATE TABLE KHACHHANG (
    MAKH CHAR(8) PRIMARY KEY,
    TENKH NVARCHAR(30) NOT NULL,
    GIOITINH NCHAR(3) NOT NULL,
    NGAYSINH SMALLDATETIME NOT NULL,
    CCCD NVARCHAR(13) UNIQUE,
    NGAYCAP SMALLDATETIME,
    QUOCTICH NVARCHAR(30) NOT NULL,
    SODT VARCHAR(10) UNIQUE,
    EMAIL VARCHAR(50) UNIQUE,
    DIACHI NCHAR(50) NOT NULL,
    PASSWORD VARCHAR(25) NOT NULL,
    NGAYTAOTK DATETIME NOT NULL,
    MAVT CHAR(8) FOREIGN KEY REFERENCES VAITRO(MAVT)
);
GO

CREATE TABLE HOADON (
    MAHD CHAR(8) PRIMARY KEY,
    MANV CHAR(8) FOREIGN KEY REFERENCES NHANVIEN(MANV),
    MAKH CHAR(8) FOREIGN KEY REFERENCES KHACHHANG(MAKH),
    NGAYLAP DATE NOT NULL,
    SOVE INT,
    THANHTIEN MONEY,
	TINHTRANG INT
);
GO

CREATE TABLE HANGVE (
    MAHV CHAR(8) PRIMARY KEY,
    TENHANGVE NVARCHAR(20) NOT NULL
);
GO

CREATE TABLE VE (
    MAVE CHAR(8) PRIMARY KEY,
    MAHV CHAR(8) FOREIGN KEY REFERENCES HANGVE(MAHV),
    MACB CHAR(8) FOREIGN KEY REFERENCES CHUYENBAY(MACB),
    MAHD CHAR(8) FOREIGN KEY REFERENCES HOADON(MAHD),
    GHE CHAR(3) NOT NULL,
    GIAVE MONEY NOT NULL,
);
GO

--Thêm ràng buộc
-->Bảng NHANVIEN<--
ALTER TABLE NHANVIEN ADD CONSTRAINT CHK_SDT CHECK (SODT LIKE '0%');

ALTER TABLE NHANVIEN
ADD CONSTRAINT CHK_NGAYVAOLAM_NGAYSINH CHECK (NGAYVAOLAM > NGAYSINH);

ALTER TABLE NHANVIEN
ADD CONSTRAINT CHK_NGAYTAOTK CHECK (NGAYTAOTK >= NGAYVAOLAM AND NGAYTAOTK <= GETDATE());

--> Bảng KHACHHANG <--
ALTER TABLE KHACHHANG
ADD CONSTRAINT CHK_NGAYCAP_NGAYSINH CHECK (NGAYCAP > NGAYSINH);

ALTER TABLE KHACHHANG ADD CONSTRAINT CHK_SDT_KH CHECK (SODT LIKE '0%');

ALTER TABLE KHACHHANG
ADD CONSTRAINT CHK_NGAYTAOTK_KH CHECK (NGAYTAOTK <= GETDATE());

--> Bảng VE <--
ALTER TABLE VE
ADD CONSTRAINT CHK_GIAVE CHECK (GIAVE >=0)

--> Bảng CHUYENBAY <--
ALTER TABLE CHUYENBAY
ADD CONSTRAINT CHK_SOGHEHANGTHUONGCONLAI CHECK (SOGHEHANGTHUONGCONLAI >= 0);

ALTER TABLE CHUYENBAY
ADD CONSTRAINT CHK_SOGHEHANGVIPCONLAI CHECK (SOGHEHANGVIPCONLAI >= 0);

--> Bảng MAYBAY

ALTER TABLE MAYBAY
ADD CONSTRAINT CHK_SOGHETHUONG CHECK (SOGHETHUONG >= 0);

ALTER TABLE MAYBAY
ADD CONSTRAINT CHK_SOGHEVIP CHECK (SOGHEVIP >= 0);

--> Bảng TUYENBAY <--

ALTER TABLE TUYENBAY
ADD CONSTRAINT CHK_MASBDI_MASBDEN CHECK (MASBDI <> MASBDEN);

--> Bảng HOADON
ALTER TABLE HOADON
ADD CONSTRAINT CHK_TINHTRANG CHECK (TINHTRANG = 0 OR TINHTRANG = 1);
