USE QUANLYCHUYENBAY
GO

CREATE FUNCTION DEM_SLKHDK_THEOTHANG (
    @p_month INT,
    @p_year INT
)
RETURNS INT
BEGIN
    DECLARE @SLKH INT;
    SELECT @SLKH = COUNT(*)
    FROM KHACHHANG
    WHERE MONTH(NGAYTAOTK) = @p_month AND YEAR(NGAYTAOTK) = @p_year;
    RETURN @SLKH;
END;
GO

CREATE FUNCTION DEM_SLCB_THEOTHANG (
	@p_month INT,
	@p_year INT
)
RETURNS INT
BEGIN
	DECLARE @SLCB INT;
	SELECT @SLCB = COUNT(*)
	FROM CHUYENBAY
	WHERE MONTH(NGAYKHOIHANH) = @p_month AND YEAR(NGAYKHOIHANH) = @p_year;
	RETURN @SLCB;
END;
GO

CREATE FUNCTION DOANHTHU (
	@p_day INT,
	@p_month INT,
	@p_year INT
)
RETURNS DECIMAL(10,2)
BEGIN 
	DECLARE @DOANHTHU DECIMAL(10,2);
	IF (@p_day IS NOT NULL AND @p_month IS NULL) OR
		(@p_month IS NOT NULL AND @p_year IS NULL)
	BEGIN
		SET @DOANHTHU = NULL;
		RETURN @DOANHTHU;
	END
	
	IF (@p_day IS NOT NULL) 
	BEGIN
		SELECT @DOANHTHU = COALESCE(SUM(HD.THANHTIEN), 0)
		FROM HOADON HD
		WHERE DAY(HD.NGAYLAP) = @p_day
			AND MONTH(HD.NGAYLAP) = @p_month
			AND YEAR(HD.NGAYLAP) = @p_year
			AND TINHTRANG = 1;
	END
	ELSE
		IF (@p_month IS NOT NULL) 
		BEGIN
			SELECT @DOANHTHU = COALESCE(SUM(HD.THANHTIEN), 0)
			FROM HOADON HD
			WHERE MONTH(HD.NGAYLAP) = @p_month
				AND YEAR(HD.NGAYLAP) = @p_year
				AND TINHTRANG = 1;
		END
		ELSE
			IF (@p_year IS NOT NULL) 
			BEGIN
				SELECT @DOANHTHU = COALESCE(SUM(HD.THANHTIEN), 0)
				FROM HOADON HD
				WHERE YEAR(HD.THANHTIEN) = @p_year
					AND TINHTRANG = 1;
			END
		
	RETURN @DOANHTHU;
END
GO

CREATE FUNCTION TIM_CHUYENBAY (
	@diem_di NVARCHAR(40),
	@diem_den NVARCHAR(40)
)
RETURNS TABLE
BEGIN
	DECLARE @masbdi CHAR(8), @masbden CHAR(8)
	SELECT @masbdi = SB.MASB
	FROM SANBAY SB
	WHERE DIADIEM = @diem_di

	SELECT @masbden = SB.MASB
	FROM SANBAY SB
	WHERE DIADIEM = @diem_den

	SELECT CB.MACB, GIOKHOIHANH, CAST(((DATEPART(HOUR, GIOKHOIHANH) * 3600 + DATEPART(MINUTE, GIOKHOIHANH) * 60 + DATEPART(SECOND, GIOKHOIHANH) +DATEPART(HOUR, THOIGIANDUKIEN) * 3600 + DATEPART(MINUTE, THOIGIANDUKIEN) * 60 + DATEPART(SECOND, THOIGIANDUKIEN)) % 86400) AS TIME) AS THOIGIANDEN, GIAVE
	FROM TUYENBAY TB
	JOIN CHUYENBAY CB ON TB.MATB = CB.MATB
	JOIN VE ON VE.MACB = CB.MACB
	WHERE MASBDI = @masbdi AND MASBDEN =masbden


	
	