USE QUANLYCHUYENBAY;

DELIMITER //
CREATE FUNCTION DEM_SLKHDK_THEOTHANG(in_p_month INT, in_p_year INT)
RETURNS INT
BEGIN
    DECLARE v_SLKH INT;
    SELECT COUNT(*) INTO v_SLKH
    FROM KHACHHANG
    WHERE MONTH(NGAYTAOTK) = in_p_month AND YEAR(NGAYTAOTK) = in_p_year;
    RETURN v_SLKH;
END;//

SELECT * FROM KHACHHANG

SELECT DEM_SLKHDK_THEOTHANG(9, 2023)



DELIMITER //
CREATE FUNCTION DEM_SLCB_THEOTHANG(in_p_month INT, in_p_year INT)
RETURNS INT
BEGIN
    DECLARE v_SLCB INT;
    SELECT COUNT(*) INTO v_SLCB
    FROM CHUYENBAY
    WHERE MONTH(NGAYKHOIHANH) = in_p_month AND YEAR(NGAYKHOIHANH) = in_p_year;
    RETURN v_SLCB;
END;//
DELIMITER ;



DELIMITER //
CREATE FUNCTION DOANHTHU(in_p_day INT, in_p_month INT, in_p_year INT)
RETURNS DECIMAL(10,2)
BEGIN 
    DECLARE v_DOANHTHU DECIMAL(10,2);
    IF (in_p_day IS NOT NULL AND in_p_month IS NULL) OR
       (in_p_month IS NOT NULL AND in_p_year IS NULL) THEN
        SET v_DOANHTHU = NULL;
        RETURN v_DOANHTHU;
    END IF;
    
    IF (in_p_day IS NOT NULL) THEN
        SELECT COALESCE(SUM(HD.THANHTIEN), 0) INTO v_DOANHTHU
        FROM HOADON HD
        WHERE DAY(HD.NGAYLAP) = in_p_day
            AND MONTH(HD.NGAYLAP) = in_p_month
            AND YEAR(HD.NGAYLAP) = in_p_year
            AND TINHTRANG = 1;
    ELSEIF (in_p_month IS NOT NULL) THEN
        SELECT COALESCE(SUM(HD.THANHTIEN), 0) INTO v_DOANHTHU
        FROM HOADON HD
        WHERE MONTH(HD.NGAYLAP) = in_p_month
            AND YEAR(HD.NGAYLAP) = in_p_year
            AND TINHTRANG = 1;
    ELSEIF (in_p_year IS NOT NULL) THEN
        SELECT COALESCE(SUM(HD.THANHTIEN), 0) INTO v_DOANHTHU
        FROM HOADON HD
        WHERE YEAR(HD.THANHTIEN) = in_p_year
            AND TINHTRANG = 1;
    END IF;
    
    RETURN v_DOANHTHU;
END;//
DELIMITER ;


