USE QUANLYCHUYENBAY;

-- View để ẩn mật khẩu cho nhân viên
CREATE VIEW NHANVIEN_VIEW AS
SELECT MANV, TENNV, DIACHI, SODT, NGAYSINH, NGAYVAOLAM, GIOITINH, EMAIL, NGAYTAOTK
FROM NHANVIEN;

REVOKE SELECT ON QUANLYCHUYENBAY.NHANVIEN FROM nhanvien_role;
GRANT SELECT ON QUANLYCHUYENBAY.NHANVIEN_VIEW TO nhanvien_role;

-- View để ẩn mật khẩu cho khách hàng 
CREATE VIEW KHACHHANG_VIEW AS
SELECT MAKH, TENKH, GIOITINH, NGAYSINH, QUOCTICH, SODT, EMAIL, DIACHI, NGAYTAOTK
FROM KHACHHANG;

REVOKE SELECT ON QUANLYCHUYENBAY.KHACHHANG FROM nhanvien_role;
GRANT SELECT ON QUANLYCHUYENBAY.KHACHHANG_VIEW TO nhanvien_role;

-- View để xem chi tiết chuyến bay
CREATE VIEW THONGTIN_CHUYENBAY_VIEW AS
SELECT CB.MACB, NGAYKHOIHANH, GIOKHOIHANH, GIOHACANH, GIAVE, TENHANGVE
FROM CHUYENBAY CB JOIN VE ON CB.MACB = VE.MACB 
	JOIN HANGVE HV ON VE.MAHV = HV.MAHV
ORDER BY CB.MACB;
	
-- View để xem tổng tiền mua hàng của khách hàng
CREATE VIEW TONGTIEN_KHACHHANG_VIEW AS
SELECT KH.MAKH, TENKH, COALESCE(SUM(HD.THANHTIEN),0) AS TONGTIEN
FROM KHACHHANG KH LEFT JOIN HOADON HD ON KH.MAKH = HD.MAKH
WHERE TINHTRANG = 1 
GROUP BY KH.MAKH
ORDER BY KH.MAKH;

-- View để xem hóa đơn chưa thanh toán
CREATE VIEW HOADON_CHUATHANHTOAN AS
SELECT MAHD, MANV, MAKH, NGAYLAP
FROM HOADON
WHERE TINHTRANG = 0;

-- View để xem hóa đơn đã thanh toán
CREATE VIEW HOADON_DATHANHTOAN AS
SELECT MAHD, MANV, MAKH, NGAYLAP
FROM HOADON 
WHERE TINHTRANG = 1;


