USE QUANLYCHUYENBAY;

DELIMITER //
CREATE FUNCTION FUNC_CUSTOMER_SIGNUPS_BY_MONTH(in_p_month INT, in_p_year INT)
RETURNS INT
BEGIN
    DECLARE v_CUSCOUNT INT;
    SELECT COUNT(*) INTO v_CUSCOUNT
    FROM CUSTOMER
    WHERE MONTH(SIGNUP_DATE) = in_p_month AND YEAR(SIGNUP_DATE) = in_p_year;
    RETURN v_CUSCOUNT;
END;//
DELIMITER ;


DELIMITER //
CREATE FUNCTION FUNC_FLIGHTS_BY_MONTH(in_p_month INT, in_p_year INT)
RETURNS INT
BEGIN
    DECLARE v_FLIGHTS INT;
    SELECT COUNT(*) INTO v_FLIGHTS
    FROM FLIGHT
    WHERE MONTH(DEPARTURE_DATE) = in_p_month AND YEAR(DEPARTURE_DATE) = in_p_year;
    RETURN v_FLIGHTS;
END;//
DELIMITER ;


DELIMITER //
CREATE FUNCTION FUNC_REVENUE(in_p_day INT, in_p_month INT, in_p_year INT)
RETURNS DECIMAL(10,2)
BEGIN 
    DECLARE v_REVENUE DECIMAL(10,2);
    IF (in_p_day IS NOT NULL AND in_p_month IS NULL) OR
       (in_p_month IS NOT NULL AND in_p_year IS NULL) THEN
        SET v_REVENUE = NULL;
        RETURN v_REVENUE;
    END IF;
    
    IF (in_p_day IS NOT NULL) THEN
        SELECT COALESCE(SUM(IV.TOTAL), 0) INTO v_REVENUE
        FROM INVOICE IV
        WHERE DAY(IV.INVOICE_DATE) = in_p_day
            AND MONTH(IV.INVOICE_DATE) = in_p_month
            AND YEAR(IV.INVOICE_DATE) = in_p_year
            AND STATUS = 1;
    ELSEIF (in_p_month IS NOT NULL) THEN
        SELECT COALESCE(SUM(IV.TOTAL), 0) INTO v_REVENUE
        FROM INVOICE IV
        WHERE MONTH(IV.INVOICE_DATE) = in_p_month
            AND YEAR(IV.INVOICE_DATE) = in_p_year
            AND STATUS = 1;
    ELSEIF (in_p_year IS NOT NULL) THEN
        SELECT COALESCE(SUM(IV.TOTAL), 0) INTO v_REVENUE
        FROM INVOICE IV
        WHERE YEAR(IV.TOTAL) = in_p_year
            AND STATUS = 1;
    END IF;
    
    RETURN v_REVENUE;
END;//
DELIMITER ;


DELIMITER //
CREATE FUNCTION FUNC_SALT() RETURNS VARCHAR(10)
BEGIN
	DECLARE chars VARCHAR(255) DEFAULT 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
	DECLARE salt VARCHAR(255) DEFAULT '';
	DECLARE i INT DEFAULT 0;
	WHILE i < 10 DO
		SET salt = CONCAT(salt, SUBSTRING(chars, FLOOR(1 + RAND() * CHAR_LENGTH(chars)), 1));
		SET i = i + 1;
  END WHILE;
  RETURN salt;
END;//
DELIMITER ;

